name: dyslexiease
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.0
  google_sign_in: ^5.4.2
  flutter_dotenv: ^5.2.1

  # New Dependencies
  file_picker: ^6.1.1       # For selecting PDFs and other files
  image_picker: ^1.0.4      # For selecting images from gallery/camera
  http: ^0.13.6             # For making API requests to the cloud function
  path: ^1.8.3              # For file path operations
  mime: ^1.0.4              # To get MIME type of files
  http_parser: ^4.0.2       # For parsing HTTP requests

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png        # Your app icon (from the SplashScreen)
    - assets/teacher.png     # Your mascot image
    - assets/pdf.png         # PDF icon
    - assets/camera.png      # Camera icon
    - assets/note.png        # Note icon
    - assets/bot.png         # Bot icon
    - assets/programmer.png  # scan pdf mascot
    - assets/photographer.png # scan picture mascot
    - assets/welcome.png      # auth page mascot

  fonts:
    - family: OpenDyslexic  # The name you'll use in your code
      fonts:
        - asset: fonts/OpenDyslexic-Regular.otf
        - asset: fonts/OpenDyslexic-Bold.otf
          weight: 700  # or FontWeight.bold
        - asset: fonts/OpenDyslexic-Italic.otf
          style: italic
