// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7oBXEMm7k92lLlrGpShgGCVPZMJncTMY',
    appId: '1:276990450661:web:8d3f2efc0ffa25cea6ed0c',
    messagingSenderId: '276990450661',
    projectId: 'dyslexiease',
    authDomain: 'dyslexiease.firebaseapp.com',
    storageBucket: 'dyslexiease.firebasestorage.app',
    measurementId: 'G-FZ2GD05RYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJWCJLsKgbEHMPQeYrmugF6ww6zPCFHUw',
    appId: '1:276990450661:android:8a9c4ace51a4cf22a6ed0c',
    messagingSenderId: '276990450661',
    projectId: 'dyslexiease',
    storageBucket: 'dyslexiease.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApSTVmcpaObutAFl1iYa53sXK8jM7qHKc',
    appId: '1:276990450661:ios:aefc31a5e1d1fc88a6ed0c',
    messagingSenderId: '276990450661',
    projectId: 'dyslexiease',
    storageBucket: 'dyslexiease.firebasestorage.app',
    iosBundleId: 'com.example.dyslexiease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApSTVmcpaObutAFl1iYa53sXK8jM7qHKc',
    appId: '1:276990450661:ios:aefc31a5e1d1fc88a6ed0c',
    messagingSenderId: '276990450661',
    projectId: 'dyslexiease',
    storageBucket: 'dyslexiease.firebasestorage.app',
    iosBundleId: 'com.example.dyslexiease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7oBXEMm7k92lLlrGpShgGCVPZMJncTMY',
    appId: '1:276990450661:web:748baf16f7cf066aa6ed0c',
    messagingSenderId: '276990450661',
    projectId: 'dyslexiease',
    authDomain: 'dyslexiease.firebaseapp.com',
    storageBucket: 'dyslexiease.firebasestorage.app',
    measurementId: 'G-BE2ZPBV6FQ',
  );
}
